[package]
name = "bstr"
version = "0.2.0"
edition = "2021"

[lib]
name = "bstr"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
base64 = "0.21"
bytes = "1"
bytestring = "1"
libc = "0.2"
